# Generated by Django 6.0.3 on 2026-07-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_currency_payment_payment_amount_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='direction',
            field=models.CharField(choices=[('money_out', 'Money out'), ('money_in', 'Money in')], max_length=10),
        ),
    ]
